name: PAWGamesHub
version: 1.0.0
main: us.pawgames.hub.PAWHub
author: KENisFIS
website: http://www.pawgames.us/
commands:
  pet:
    usage: /<command> 
    description: /pawtest (runs debug test)
    permission: paw.hub.pet